context("testing mra_wendland_2d")

test_that("illegal input", {
    locs <- matrix(NA, 10, 3)
    expect_error(mra_wendland_2d(locs), "locs must be a numeric matrix with N rows and 2 columns")
    locs <- matrix(NA, 10, 2)
    expect_error(mra_wendland_2d(locs), "locs must be a numeric matrix with N rows and 2 columns")
    locs <- matrix("aaa", 10, 2)
    expect_error(mra_wendland_2d(locs), "locs must be a numeric matrix with N rows and 2 columns")
    locs <- matrix(1:20, 10, 2)
    expect_error(mra_wendland_2d(locs, M = 3.5), "the number of resolutions M must be a positive integer")
    expect_error(mra_wendland_2d(locs, M = NA), "the number of resolutions M must be a positive integer")
    expect_error(mra_wendland_2d(locs, M = "aaa"), "the number of resolutions M must be a positive integer")
    expect_error(mra_wendland_2d(locs, n_neighbors = 3.5), "n_neighbors must be a positive integer")
    expect_error(mra_wendland_2d(locs, n_neighbors = NA), "n_neighbors must be a positive integer")
    expect_error(mra_wendland_2d(locs, n_neighbors = "aaa"), "n_neighbors must be a positive integer")
    expect_error(mra_wendland_2d(locs, n_coarse_grid = 3.5), "n_coarse_grid must be a positive integer")
    expect_error(mra_wendland_2d(locs, n_coarse_grid = NA), "n_coarse_grid must be a positive integer")
    expect_error(mra_wendland_2d(locs, n_coarse_grid = "aaa"), "n_coarse_grid must be a positive integer")
    expect_error(mra_wendland_2d(locs, n_padding = 3.5), "n_padding must be a positive integer")
    expect_error(mra_wendland_2d(locs, n_padding = NA), "n_padding must be a positive integer")
    expect_error(mra_wendland_2d(locs, n_padding = "aaa"), "n_padding must be a positive integer")
    expect_error(mra_wendland_2d(locs, use_spam = 3.5), "use_spam must be either TRUE or FALSE")
    expect_error(mra_wendland_2d(locs, use_spam = NA), "use_spam must be either TRUE or FALSE")
    expect_error(mra_wendland_2d(locs, use_spam = "aaa"), "use_spam must be either TRUE or FALSE")

    expect_error(mra_wendland_2d(locs, M = 4, n_coarse_grid = 3), "There are too many resolutions to form a reliable grid. Reduce M and try again.")
})
